version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '01:00'
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  labels:
    - "dependencies"
    - "ruby"
    - "automerge"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '01:00'
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "javascript"
    - "automerge"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '01:00'
    timezone: Europe/Berlin
  labels:
    - "dependencies"
    - "actions"
    - "automerge"
